### ISSUE TITLE
Cofunctor is not cofunctor

### ISSUE THREAD

**Issue by Jacoby6000** [dehun/learn-fp#11]
Your implementation of cofunctor is actualy `Contravariant Functor`.  A real cofunctor is identical to functor.

Incorrectly naming it `Cofunctor` is bound to confuse people whenever they try to understand that a `CoFoo` is just `Foo` with reversed arrows.

```haskell
fmap   :: (a -> b) -> f a -> f b
coFmap :: (b -> a) -> f b -> f a

contramap :: (b -> a) -> f a -> f b
```

Often times, people will just use the name `Contravariant` in place of `Contravariant Functor`.  Please do not use `Cofunctor` to mean `Contravariant Functor`, though.

**Comment by dehun** [comment]
Indeed this brings some confusion. I will rename it somewhere this week. Thanks for pointing it!

**Comment by tonymorris** [comment]
`fmap :: (a -> b) -> f a -> f b`

```
class Contravariant f where
  contramap :: (b -> a) -> f a -> f b
```

**Comment by dehun** [comment]
Renamed in both master and answers. 
Thank you!
